# Generated by Django 2.1.7 on 2019-02-15 20:19

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='texto',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 2, 15, 20, 19, 22, 262328, tzinfo=utc)),
        ),
    ]
